#!/bin/bash

set -e

BASE_PATH=$1
shift

while [ $# -gt 0 ]; do
  case "$1" in
    --mysql-connector-version=*)
      MYSQL_CONNECTOR_VERSION=${1#*=}
      ;;
    *)
      printf "Error: Invalid argument: %s\n" "$1"
      exit 1
  esac
  shift
done

SQOOP_HOME=/usr/lib/sqoop
SQOOP_LIB=$SQOOP_HOME/lib

MYSQL_CONNECTOR_VERSION=${MYSQL_CONNECTOR_VERSION:-5.1.35}
MYSQL_CONNECTOR_RELEASE=mysql-connector-java-$MYSQL_CONNECTOR_VERSION
MYSQL_CONNECTOR_FILENAME=$MYSQL_CONNECTOR_RELEASE.tar.gz
MYSQL_CONNECTOR_S3_URL=$BASE_PATH/$MYSQL_CONNECTOR_FILENAME

hadoop dfs -get $MYSQL_CONNECTOR_S3_URL ./$MYSQL_CONNECTOR_FILENAME
tar -xzf $MYSQL_CONNECTOR_FILENAME
sudo cp $MYSQL_CONNECTOR_RELEASE/$MYSQL_CONNECTOR_RELEASE-bin.jar $SQOOP_LIB/
