- name: configure jenkins scheduler
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    JENKINS_EXTRA_PKGS:
      - libmysqlclient-dev
      - mysql-client
      - zip
      - libpq-dev
  roles:
    - python
    - s3cmd
    - jenkins
  tasks:
    - name: Checkout analytics configuration
      sudo_user: '{{ jenkins_user }}'
      git: >
        dest=/home/jenkins/analytics-configuration
        repo={{ analytics_configuration_repo }}
        version={{ analytics_configuration_version }}

    - name: Checkout analytics pipeline
      sudo_user: '{{ jenkins_user }}'
      git: >
        dest=/home/jenkins/analytics-tasks
        repo={{ analytics_pipeline_repo }}
        version={{ analytics_pipeline_version }}

    - name: Set up emr variables file
      template: >
        src=templates/emr-vars.yml.j2 dest=/home/jenkins/emr-vars.yml
        owner={{ jenkins_user }}

    - name: Set up ec2 configuration file
      template: >
        src=templates/ec2.ini.j2 dest=/home/jenkins/ec2.ini
        owner={{ jenkins_user }}
